Repository FEMessage/el-form-renderer, pull requests merged in 2019-07, with the labels that each got.

#46 docs: add english docs
  README-en.md
Labels: enhancement

#49 docs(el): 补充自定义组件传props示例
  docs/el.md
Labels: documentation

#56 docs: 删除旧的英文readme
  README.en.md
Labels: documentation

#48 docs: fix package name
  README.md
Labels: documentation

#63 docs: 添加自定义组件指南
  README-en.md
  README.md
  docs/guide-custom-component.md
  styleguide.config.js
Labels: documentation

#64 feat: 添加 hidden 功能
  docs/hidden.md
  src/el-form-renderer.md
  src/mixins/enable-when.js
  src/mixins/hidden.js
  src/mixins/package-option.js
  src/render-form-item.js
  test/mixin-hidden.test.js
Labels: enhancement

#69 feat: 新增属性 on，可以绑定组件的事件
  docs/at-change.md
  docs/on.md
  package.json
  src/el-form-renderer.md
  src/render-form-item.js
  styleguide.config.js
  styleguide/index.js
  styleguide/upload-to-ali.js
  yarn.lock
Labels: enhancement

#70 fix(setOptions): 修复setOptions
  docs/set-options.md
  src/el-form-renderer.js
  test/init-item-options.test.js
  test/set-options.test.js
Labels: bug

#72 docs: README内图片使用语雀cdn
  README.md
  assets/form.gif
  assets/image-20181211165604688.png
  assets/image-20181211165959102.png
  assets/image-20181211170318736.png
  assets/image-20181211171344921.png
  assets/image-20181211171719502.png
  assets/image-20181211172910592.png
  assets/image-20181211175701822.png
  assets/image-20181221163020715.png
  assets/image-20181221194652643.png
  assets/image-20190319195020391.png
Labels: documentation

#73 feat: 支持自定义组件自定义 rules
  docs/guide-custom-rules-in-custom-component.md
  src/custom-component-rules.js
  src/el-form-renderer.js
  src/transform-content.js
  test/config.js
  test/custom-component-rules.test.js
  test/transform-content.test.js
Labels: enhancement

#74 docs: 完善文档
  docs/guide-custom-rules-in-custom-component.md
Labels: documentation

#75 docs: 修复代码展示
  docs/guide-custom-rules-in-custom-component.md
Labels: documentation

#76 fix: 修复 input 框不能输入空格的问题
  src/render-form-item.js
Labels: bug

#78 fix(hack): 修复多选select组件 重置时 Vue 报错的问题
  package.json
  src/el-form-renderer.js
  test/reset-fields.test.js
  yarn.lock
Labels: hack

#79 chore: 更新 cli 配置
  .babelrc.js
  .stylelintrc
  notify.sh
  package.json
  styleguide.config.js
  yarn.lock
Labels: chore

#80 chore: 解决 yarn 冲突问题
  yarn.lock
Labels: chore

#82 docs: add english guide
  README-en.md
  docs/guide-en-custom-component.md
  docs/guide-en-custom-rules-in-custom-component.md
Labels: documentation

#83 feat: 可以覆盖自定义组件内部的校验规则
  docs/guide-custom-rules-in-custom-component.md
  docs/guide-en-custom-rules-in-custom-component.md
  src/custom-component-rules.js
  src/el-form-renderer.md
Labels: enhancement

#85 docs: update README badges & contributing
  .github/badge.yml
  .grenrc.js
  README-zh.md
  README.md
  package.json
Labels: documentation
