Repository FEMessage/el-form-renderer, pull requests merged in 2019-11, with the labels that each got.

#119 refactor: 不依赖特定的 element 包
  src/el-form-renderer.js
Labels: refactor

#121 docs: 切换图床
  README-zh.md
  README.md
Labels: documentation

#120 feat: options支持通过remote的方式获取
  .eslintrc.js
  docs/remote.md
  package.json
  src/el-form-renderer.md
  src/render-form-item.js
  styleguide/index.js
  yarn.lock
Labels: enhancement

#131 fix: setOptions 失效
  src/render-form-item.js
Labels: bug

#130 fix: disabled not working
  docs/disabled.md
  src/el-form-renderer.js
Labels: bug
