Repository FEMessage/el-form-renderer, pull requests merged in 2020-01, with the labels that each got.

#152 feat: 新增 readonly 功能 & 重构 render 函数为 template
  docs/el.md
  docs/readonly.md
  src/el-form-renderer.md
  src/el-form-renderer.vue
  src/index.js
  src/render-form-group.js
  src/render-form-group.vue
  src/render-form-item.vue
  styleguide.config.js
Labels: enhancement

#153 fix: 修复 test & 增加 pre-push 钩子
  jest.config.js
  package.json
  test/init-item-options.test.js
  test/mixin-hidden.test.js
  test/reset-fields.test.js
  test/set-options.test.js
  yarn.lock
Labels: bug

#154 fix: 原 babel 有时会出问题
  .babelrc.js
Labels: bug

#155 chore: 添加 class 提高辨识度
  src/el-form-renderer.vue
Labels: chore, improvement

#156 chore: 添加 class (#155)
  src/el-form-renderer.vue
Labels: chore
